### ISSUE TITLE
Mergegame low difficulty

### ISSUE THREAD

**Issue by Builder18** [lealcy/lealcy.github.io#1]
Perhaps mergegame could unlock new resources based on player's current money?

@lealcy

**Comment by lealcy** [comment]
Thank you for your feedback and sorry for the delayed response. I was just prototyping with this game. There is a black space where it would have upgrades to be bought but I never implemented then. If I would touch this code now it would be to rewrite it yet again, maybe to test some framework ;). Best of wishes!

**Comment by Builder18** [comment]
Alright, thank you for answer! :)
